http_jar(
    name = "com_github_google_copybara",
    # Fill in from https://github.com/google/copybara/releases/download/[version]/copybara_deploy.jar.sha256
    sha256 = "fee957e50f8fe958a20dc77046977dce12404221542f35367d25ef7ce937eb1a",
    urls = ["https://github.com/google/copybara/releases/download/v20250728/copybara_deploy.jar"],
)

